server:
  port: 8900
spring:
  application:
    name: zuul
management:
  security:
    enabled: false

zuul:
  routes:
    customer-service:
      path: /feign/**
      strip-prefix: false
      serviceId: customer-service
#  prefix: "/api"
#  strip-prefix: false
  ignored-services: "*"

customer-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:9090/
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
ribbon:
  eureka:
    enabled: false
